### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by tleen** [jarofghosts/fs-find-root#1]
I believe when asked to search to the top of the directory tree without finding the file the find method eventually throws a TypeError.

**Comment by jarofghosts** [comment]
i just tested this and couldn't reproduce. is there any way you could paste the code in question? or a test case?

**Comment by tleen** [comment]
Let me see if I can make an isolated one, the one I had is from [here](https://github.com/tleen/docs-for/blob/77238ab031aeb68c86b49e66db0d359f8b8dd504/test/index.js#L49).

**Comment by tleen** [comment]
My fault. My error. Sorry!
